plugins {
    id 'com.android.application'
}

android {
    namespace 'in.gov.sail.steelhub'
    compileSdk 34
    buildToolsVersion "34.0.0"

    defaultConfig {
        applicationId "in.gov.sail.steelhub"
        minSdk 24
        targetSdk 34
        versionCode 1
        versionName "1.0.0"

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }

    signingConfigs {
        release {
            storeFile file('release.keystore')
            storePassword 'sailsteelhub2026'
            keyAlias 'sailsteelhub'
            keyPassword 'sailsteelhub2026'
        }
    }

    buildTypes {
        release {
            signingConfig signingConfigs.release
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
        debug {
            debuggable true
            applicationIdSuffix ".debug"
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}

dependencies {
    implementation 'androidx.appcompat:appcompat:1.7.0'
    implementation 'com.google.android.material:material:1.12.0'
    implementation 'androidx.swiperefreshlayout:swiperefreshlayout:1.1.0'
    implementation 'androidx.activity:activity:1.9.1'
    implementation 'androidx.webkit:webkit:1.11.0'
}
